CREATE TABLE USERS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    LAST_NAME VARCHAR(80),
    FIRST_NAME VARCHAR(80),
    MIDDLE_NAME VARCHAR(80)
);

CREATE TABLE TUI_VIEW_MODELS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    PARENT INTEGER REFERENCES TUI_VIEW_MODELS(ID),
    NAME VARCHAR(80)
);

CREATE TABLE TUI_VIEW_MODEL_ACTIONS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    VIEW_MODEL INTEGER REFERENCES TUI_VIEW_MODELS(ID),
    NAME VARCHAR(80),
    NOTE VARCHAR(1024)
);

CREATE TABLE TUI_PERMISSIONS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    VIEW_MODEL_ACTION INTEGER REFERENCES TUI_VIEW_MODEL_ACTIONS(ID),
    USER_ID INTEGER REFERENCES USERS(ID),
    DATE_EXPIRE DATE
);