SET SQL DIALECT 3;

SET NAMES UTF8;

CREATE DATABASE 'E:\MyProjects\Firebird\Data\test.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 4096
DEFAULT CHARACTER SET UTF8;

CREATE TABLE USERS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    LOGIN VARCHAR(80),
    LAST_NAME VARCHAR(80),
    FIRST_NAME VARCHAR(80),
    MIDDLE_NAME VARCHAR(80)
);

CREATE TABLE TUI_VIEW_MODELS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    PARENT INTEGER REFERENCES TUI_VIEW_MODELS(ID),
    NAME VARCHAR(80)
);

CREATE TABLE TUI_VIEW_MODEL_ACTIONS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    VIEW_MODEL INTEGER REFERENCES TUI_VIEW_MODELS(ID),
    NAME VARCHAR(80),
    NOTE VARCHAR(1024)
);

CREATE TABLE TUI_PERMISSIONS
(
    ID INTEGER NOT NULL PRIMARY KEY,
    VIEW_MODEL_ACTION INTEGER REFERENCES TUI_VIEW_MODEL_ACTIONS(ID),
    USER_ID INTEGER REFERENCES USERS(ID),
    DATE_EXPIRE DATE
);

INSERT INTO USERS(ID, LOGIN, LAST_NAME, FIRST_NAME, MIDDLE_NAME) VALUES (1, 'Sidorov', 'Сидоров', 'Иван', 'Иванович');
INSERT INTO USERS(ID, LOGIN, LAST_NAME, FIRST_NAME, MIDDLE_NAME) VALUES (2, 'Kornilov', 'Корнилов', 'Алексей', 'Альбертович');
INSERT INTO USERS(ID, LOGIN, LAST_NAME, FIRST_NAME, MIDDLE_NAME) VALUES (3, 'Morozova', 'Морозова', 'Инна', 'Платоновна');

INSERT INTO TUI_VIEW_MODELS(ID, PARENT, "NAME") VALUES (1, null, 'Main');
INSERT INTO TUI_VIEW_MODELS(ID, PARENT, "NAME") VALUES (2, 1, 'User');
INSERT INTO TUI_VIEW_MODELS(ID, PARENT, "NAME") VALUES (3, 1, 'Options');

INSERT INTO TUI_VIEW_MODEL_ACTIONS(ID, VIEW_MODEL, "NAME", NOTE) VALUES (1, 2, 'Открытие', 'Возможность открытия');
INSERT INTO TUI_VIEW_MODEL_ACTIONS(ID, VIEW_MODEL, "NAME", NOTE) VALUES (2, 2, 'Изменение', 'Возможность изменения');
INSERT INTO TUI_VIEW_MODEL_ACTIONS(ID, VIEW_MODEL, "NAME", NOTE) VALUES (3, 2, 'Печать', 'Возможность печати');
INSERT INTO TUI_VIEW_MODEL_ACTIONS(ID, VIEW_MODEL, "NAME", NOTE) VALUES (4, 3, 'Открытие', 'Возможность открытия');
INSERT INTO TUI_VIEW_MODEL_ACTIONS(ID, VIEW_MODEL, "NAME", NOTE) VALUES (5, 3, 'Изменение', 'Возможность изменения');